### ISSUE TITLE
Release tags

### ISSUE THREAD

**Issue by olgeni** [SenecaSystems/sorted_set#6]
Hi,

Not really an issue, but could you set release tags for sorted_set and red_black_tree? It would be useful to build FreeBSD packages and stay up to date.

**Comment by tyre** [comment]
Sure thing! To be clear you're looking for tags on commits when the versions change?

**Comment by olgeni** [comment]
That's it - with release tags I get a new item in the atom feed of releases and can update the port with Makefiles like this:

https://svnweb.freebsd.org/ports/head/devel/elixir-calendar/Makefile?revision=391977&view=markup

Then everybody gets a new package :)

**Comment by tyre** [comment]
Right on!

I've tagged the current version and will do my best to tag all future releases. Thanks for teaching me something new :)

https://github.com/SenecaSystems/sorted_set/tree/v1.1.0

**Comment by olgeni** [comment]
Looks great :+1: do you have one for red_black_tree too?

**Comment by tyre** [comment]
Just pushed: https://github.com/SenecaSystems/red_black_tree/tree/v1.2.0

**Comment by olgeni** [comment]
Done - here we go:

https://svnweb.freebsd.org/ports?view=revision&revision=392445
https://svnweb.freebsd.org/ports?view=revision&revision=392446

Thanks!

**Comment by tyre** [comment]
Awesome, thank you @olgeni!
